### ISSUE TITLE
STATUS_DLL_NOT_FOUND on Windows

### ISSUE THREAD

**Issue by That3Percent** [jvo203/zfp-sys#1]
This will be my first crate which builds something as a dependency, so I'm not sure if I'm just doing this wrong.

I'm using `zfp-sys` via `ndarray-zfp-rs`. I installed the Visual Studio Build tools, added cmake to the PATH, and installed LLVM in order to get the `zfp-sys` crate to build.

The test that I am running exits the process with `exit code: 0xc0000135, STATUS_DLL_NOT_FOUND`.

Is there anything else I need to set up to get this crate up and running?

**Comment by jvo203** [comment]
Hi, sorry for a delay, have just noticed this issue. Usually I use Linux and macOS for development hence these bindings have not been tested under Windows at all. I will check it out soon.

**Comment by jvo203** [comment]
By the way, there seems to be no GitHub repository for ndarray-zfp-rs anymore (at least I cannot find it). It is listed on crates though... Have you got any simple example for ndarray-zfp-rs that I might test?

**Comment by That3Percent** [comment]
I'm not super interested in using `ndarray-zfp-rs`, I was just using it to get a jumpstart on using the `zfp-sys` API (which seems pretty involved based on the number of names exported). Eventually, I think I'd like to just use `zfp-sys` directly. Here's a small repro:

Cargo.toml:
```toml
[dependencies]
ndarray-zfp-rs = "0.1.0"
ndarray = "0.13.0"
```

main.rs
```rust
use ndarray_zfp_rs::Zfp;
use ndarray;

fn main() {
    let data = ndarray::Array1::from(vec![1.0]);
    let bin = data.zfp_compress_with_header(0.1).unwrap();
    dbg!(bin);
}
```

Even though the repository for `ndarray-zfp-sys` is gone, the source persists on docs.rs ([here](https://docs.rs/crate/ndarray-zfp-rs/0.1.0/source/))

If I can get `zfp-sys` working reliably I'd like to use it as the float compressor in my serialization system for data - [Tree-Buf](https://github.com/That3Percent/tree-buf)

**Comment by jvo203** [comment]
OK, thank you. I will give it a try in a spare time. However, here is a quick thought. I doubt if the underlying ZFP library compiles on Windows. It is probably {Linux,macOS}-only. If ZFP does not compile in Windows then the bindings to it (zfp-sys) would not work either.

**Comment by jvo203** [comment]
It seems the underlying ZFP library gets compiled in Windows 10 but probably as a 32-bit target. Since the Rust runtime and all the Windows 10 SDK development tools are 64-bit, linking against a 32-bit library probably results in some 32-bit runtime DLLs not being found.

The solution is to modify the zfp-sys build.rs so that cmake is forced to produce code for a 64-bit target (I guess this happens by default in Linux and macOS). I need to find the right way to do it in Windows 10 so please bear with me.

**Comment by jvo203** [comment]
I am sorry, have tried playing with 
.define("CMAKE_GENERATOR_TOOLSET", "x64")
.define("CMAKE_GENERATOR_PLATFORM", "x64") and various other options but somehow cannot get it to work properly. In the verbose error messages one can see "advapi32.dll", "ws2_32.lib", "userenv.lib" and "msvcrt.lib" so it could be that they cannot be found. I have installed the free MS Studio 2019 SDK needed by Rust, clang 10 etc.

The last time I did some Windows development had been nearly 20 years ago around the dot-com bubble. Ever since it has been Linux and recently macOS too. At present I am unable to fix it by myself due to a lack of an up-to-date experience with Windows 10. Sorry...

**Comment by That3Percent** [comment]
Ok. Unfortunately, builds are not an area of expertise for me either or I'd help out.

**Comment by jvo203** [comment]
I will investigate it further but at a slower pace, learning Windows 10 development along the way.

**Comment by jvo203** [comment]
I have updated the bindgen and cmake dependencies plus the zfp to v0.5.5. Now it seems cmake complains about not being able to find llvm-config in Windows 10. A quick Internet search shows that indeed LLVM does not ship with llvm-config in Windows 10. So the updated zfp-sys crate does not build in Windows 10 at all. Here is a cmake-rs issue: https://github.com/alexcrichton/cmake-rs/issues/81

Perhaps there might be a different way (without cmake/llvm) to generate bindings with bindgen. Will try to follow a bindgen tutorial from scratch in Windows 10.

**Comment by jvo203** [comment]
It should be possible to replace the "cmake" crate with "cc" and point it to the C source files to be compiled. Adding CUDA support might complicate things but as a first try it should be possible to make bare-bone CUDA-less cross-platform bindings with "cc".

**Comment by That3Percent** [comment]
Thanks for the updates. I'll be eager to try this as soon as it's ready.

**Comment by jvo203** [comment]
Good news,  a "cc"-based cross-platform zfp-sys-cc, found at https://github.com/jvo203/zfp-sys-cc , works OK under Windows 10.

Until it is published on crates, you can place this in your Cargo.toml:

```zfp-sys-cc = {version = "*", git = "https://github.com/jvo203/zfp-sys-cc.git"}```

And here is a sample main.rs:

```
use zfp_sys_cc::*;

fn main() {
    println!("Testing ZFP Rust bindings on Windows 10.");

    let nx = 800;
    let ny = 600;

    let mut v = vec![1.0f32; nx * ny];

    //compress the data array

    /* allocate meta data for the 2D array [nx][ny] */
    let data_type = zfp_type_zfp_type_float;
    let field = unsafe {
        zfp_field_2d(
            v.as_mut_ptr() as *mut std::ffi::c_void,
            data_type,
            nx as u32,
            ny as u32,
        )
    };

    /* allocate meta data for a compressed stream */
    let zfp = unsafe { zfp_stream_open(std::ptr::null_mut() as *mut bitstream) };

    /* set compression mode and parameters via one of three functions */
    //unsafe { zfp_stream_set_rate(zfp, 8.0, data_type, 3, 0) };
    //unsafe{ zfp_stream_set_precision(zfp, precision); }
    let tolerance = 1.0e-3;
    unsafe { zfp_stream_set_accuracy(zfp, tolerance) };

    /* allocate buffer for compressed data */
    let bufsize = unsafe { zfp_stream_maximum_size(zfp, field) };
    let mut buffer: Vec<u8> = vec![0; bufsize as usize];

    /* associate bit stream with allocated buffer */
    let stream = unsafe { stream_open(buffer.as_mut_ptr() as *mut std::ffi::c_void, bufsize) };
    unsafe {
        zfp_stream_set_bit_stream(zfp, stream);
        zfp_stream_rewind(zfp);
    }

    /* compress array and output compressed stream */
    let zfpsize = unsafe { zfp_compress(zfp, field) };
    if zfpsize == 0 {
        println!("compression failed");
    } else {
        let original_size = nx * ny * std::mem::size_of::<f32>();
        let ratio = (original_size as f64) / (zfpsize as f64);

        println!(
            "bufsize: {} bytes, original size: {} bytes, compressed size: {} bytes, ratio: {}",
            bufsize, original_size, zfpsize, ratio
        );
    }

    /* rewind compressed stream and decompress array */
    unsafe { zfp_stream_rewind(zfp) };
    let ret = unsafe { zfp_decompress(zfp, field) };
    if ret == 0 {
        println!("decompression failed");
        assert!(false);
    } else {
        println!("ret: {}", ret);
    }

    println!("decompressed data sample: {:?}", &v[0..10]);

    /* clean up */
    unsafe {
        zfp_field_free(field);
        zfp_stream_close(zfp);
        stream_close(stream);
    }
}
```

And this is the output from Windows 10:

```
PS C:\Users\クリストファー\SkyDrive\Rust\test_zfp> cargo run   
   Compiling zfp-sys-cc v0.1.0 (https://github.com/jvo203/zfp-sys-cc.git#31117fdf)
   Compiling test_zfp v0.1.0 (C:\Users\クリストファー\SkyDrive\Rust\test_zfp)                  
    Finished dev [unoptimized + debuginfo] target(s) in 3.71s                                  
     Running `target\debug\test_zfp.exe`
Testing ZFP Rust bindings on Windows 10.
bufsize: 2010024 bytes, original size: 1920000 bytes, compressed size: 161256 bytes, ratio: 11.906533710373568
ret: 161256
decompressed data sample: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
```

I will also publish the cross-platform zfp-sys-cc on crates shortly.

**Comment by jvo203** [comment]
zfp-sys-cc has been published on crates so you can now use zfp-sys-cc = "*" in Cargo.toml.

**Comment by That3Percent** [comment]
Very cool. I should be able to give this a try as early as this coming weekend. Thanks for your persistence.

**Comment by That3Percent** [comment]
Great! This works well. I've only added the compression and not yet de-compression but I think that's enough evidence.

Are there any trade-offs besides Window's support to consider using one of these zfp crates over another? Is there any reason the cc version of the crate would not just take this one over?

**Comment by jvo203** [comment]
Yes there is a significant difference. The cmake-based crate works by passing the whole ZFP source directory to cmake. cmake then compiles ZFP using the CMakeLists.txt file from the ZFP folder. Hence it compiles ZFP they way it has originally been intended, respecting all the original compiler flags etc.

The "cc" crate works differently. You do not pass it a source folder. You need to pass all the C/C++ source files one by one to "cc" (automatically build up a list of necessary source files from the ZFP folder). You also need to specify manually all the build flags (I used -O3 as originally used by ZFP) since "cc" does not make use of the Makefile nor CMakeLists.txt.

So to re-cap, with "cmake" you get a fully automatic compilation using settings as originally intended by the library author. With "cc" you perform a manual compilation process, potentially missing out on all the necessary compiler flags, switches etc. present in CMakeLists.txt etc.

Therefore "cmake" is the preferred solution. Unfortunately it does not work correctly on Windows 10, it does not seem to link against the correct Windows 10 system libraries. Perhaps in the future newer versions of the Rust cmake crate might work on Windows 10 too. "cc" works well on Linux, macOS and Windows 10 but from a "purist" point of view it is not ideal.

So for now I am inclined to leave things as they are. Have the main "workhorse" cmake-based "zfp-sys" crate plus an additional cc-based "zfp-sys-cc" with a working Windows 10 support.

Will close this issue in the zfp-sys crate. If you have any questions/issues please could you open a new issue in zfp-sys-cc.
